
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '807047B8ADAD11E31FDE2580395CA1CB'
    
_lr_action_items = {'QUOTE':([2,10,20,24,],[-15,-16,23,25,]),'ASSIGN':([16,],[20,]),'WORD':([0,1,2,4,5,6,7,8,9,10,15,16,17,19,22,23,25,],[2,8,2,2,2,2,8,-10,16,-16,-8,-14,16,-9,-7,2,-13,]),'CLOSE':([8,9,14,16,17,18,21,25,],[-10,15,19,-14,-11,22,-12,-13,]),'OPEN':([0,2,4,5,6,10,15,19,22,],[1,-15,1,1,1,-16,-8,-9,-7,]),'OPEN_DASH':([0,2,4,5,6,10,15,19,22,],[7,-15,7,7,7,-16,-8,-9,-7,]),'$end':([2,3,4,5,6,10,11,12,13,15,19,22,],[-15,0,-3,-2,-1,-16,-4,-6,-5,-8,-9,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tagname':([1,7,],[9,14,]),'content':([0,2,4,5,6,23,],[5,10,5,5,5,24,]),'element':([0,4,5,6,],[3,11,12,13,]),'close_tag':([0,4,5,6,],[4,4,4,4,]),'attribute':([9,17,],[17,17,]),'attributes':([9,17,],[18,21,]),'tag':([0,4,5,6,],[6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> element","S'",1,None,None,None),
  ('element -> tag','element',1,'p_element','parser.py',58),
  ('element -> content','element',1,'p_element','parser.py',59),
  ('element -> close_tag','element',1,'p_element','parser.py',60),
  ('element -> close_tag element','element',2,'p_element','parser.py',61),
  ('element -> tag element','element',2,'p_element','parser.py',62),
  ('element -> content element','element',2,'p_element','parser.py',63),
  ('tag -> OPEN tagname attributes CLOSE','tag',4,'p_tag','parser.py',67),
  ('tag -> OPEN tagname CLOSE','tag',3,'p_tag','parser.py',68),
  ('close_tag -> OPEN_DASH tagname CLOSE','close_tag',3,'p_close_tag','parser.py',78),
  ('tagname -> WORD','tagname',1,'p_tagname','parser.py',84),
  ('attributes -> attribute','attributes',1,'p_attributes','parser.py',88),
  ('attributes -> attribute attributes','attributes',2,'p_attributes','parser.py',89),
  ('attribute -> WORD ASSIGN QUOTE content QUOTE','attribute',5,'p_attribute','parser.py',97),
  ('attribute -> WORD','attribute',1,'p_attribute','parser.py',98),
  ('content -> WORD','content',1,'p_content','parser.py',105),
  ('content -> WORD content','content',2,'p_content','parser.py',106),
]
